### ISSUE TITLE
Replace tokens in README to use the new format, without triggering Github Secret Scanning

### ISSUE THREAD

**Issue by gr2m** [octokit/auth-token.js#197]
Follow up to https://github.com/octokit/auth-token.js/issues/195. I've inquired with GitHub Support and am awaiting their response

**Comment by 15MariamS** [comment]
The new format of GitHub tokens uses a [checksum](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/#checksum); this means that when we scan for GitHub tokens, we can check that the token input matches the checksum and eliminate fake tokens. 

In this case, you can use the checksum to generate an example token that we do not alert on.

**Comment by gr2m** [comment]
Thanks a lot Mariam, exactly the information I was looking for 👍🏼
